version: '3.8'
name: swapi-graphql

services:
  swapi-graphql-app:
    image: 'swapi-graphql-app'
    restart: on-failure
    build:
      context: .
    ports:
      - '3000:3000'
    expose:
      - 3000
    depends_on:
      - database
    env_file:
      - .env
    environment:
      - PORT=3000
      - DB_TYPE=postgres
      - DB_HOST=database
      - DB_PORT=5432
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_USER=${DB_USER}
      - DB_DATABASE=${DB_DATABASE}
      - DATABASE_URL=${DATABASE_DOCKER_URL}
      - SHADOW_DATABASE_URL=${SHADOW_DATABASE_DOCKER_URL}
  database:
    image: postgres:14.5-alpine
    restart: on-failure
    ports:
      - ${DB_PORT}:5432
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_DATABASE}
    volumes:
      - swapi-graphql-postgres:/var/lib/postgresql/data     

volumes:
  swapi-graphql-postgres:   